### ISSUE TITLE
Animation only

### ISSUE THREAD

**Issue by readergeneral** [WonderMediaProductions/Maya2glTF#118]
Hello dears,
is there a way to export the animation only (without the mesh), and the mesh only (without the animation), so i can get two glb files at the end?

in other word, we need to separate the mesh and the animation from each others, so we can mix them later..

i saw the babylonJS maya exporter can this thing, but babylon kinda slow, 
so, kindly, is there a specific Arguments/flags i can use with maya2gltf to get this done..?

thanks a lot dears

**Comment by Ziriax** [comment]
GLTF 2.0 doesn't support this out of the box, but in the develop branch that contains the future 1.0 release, we do have various flags and options for separating the mesh and animations, and a command line tool to combine them back into one large glTF if needed.

So if you want to beta test this feature, I could try to help you out.

Do you store each animation in a separate Maya scene, or do you have all anims in one Maya scene, e.g. using trax?

**Comment by readergeneral** [comment]
thanks for the quick replay,
i have one maya scene (it's just an animated character), basically the animation keys attached to the bones directly (it's a mocap -but optimised), no extra objects (one combined mesh).
 remark:... i don't really want to re-assemble the both (out-mesh.glb and the out-animation.glb) together after so into one file, i just one them separated.  
i just wanna assign the out-animation.glb to out-mesh.glb.. while the out mesh is my charecter with skin clusters and bones.

so i can generate different animations, and export them alone without the mesh to simply assign them to my character on demand. 

in this case the animation.glb  will be smaller file size,  cz it contains no real mesh data. so it's easy and lite to load.

i am using maya 19.2..

i really appreciate ur help. 
thank you

**Comment by Ziriax** [comment]
We can't completely separate the mesh, because glTF doesn't have that concept, but it is possible to store the mesh binary buffers outside of the glTF animation files.

So each animation file will be a valid glTF file that can be viewed separately, but it will refer to an external shared mesh buffer.

So the animation gtTF/glb file will have some overhead, i.e. it will still contains nodes, materials, mesh declarations, etc, but the vertices, normals, skin binding matrices, etc will be stored in an external file. 

That is the best tradeoff we could find, otherwise we would need to invent a non-compliant intermediate format.

The tricky part in Maya is that exporting a scene with different animation tends to produce a different mesh... Although the meshes seem to be compatible, they are not binary identical. We tried to identity what causes this, but had to give up, it was not something we could enforce (we use a Maya reference to the rigged mesh scene)

Are you on Windows 10?

**Comment by readergeneral** [comment]
> 
So the animation gtTF/glb file will have some overhead, i.e. it will still contains nodes, materials, mesh declarations, etc, but the vertices, normals, skin binding matrices, etc will be stored in an external file.
> 

that's seems fair to me at this moment, so i don't have to lead each. i only have to lead the animation. and the other glb with the (vertices, normals, skin binding matrices,) will be fixed and waiting to receive the animation files.. right?

i want this for a project related to medical field, i on so curious about this technique cz the size of the animation file should be less than the other glb.. so it's easy to lead.. and as i mentioned that's what i got when i used the babylon js.. but maya2glt alot faster.

yes, 'm using win10, 

so dear, have any point to start with..
you have mentioned the version 1.0 in the dev section?
is it the (7de822c)? because this is what i am using now.. 
i have to say that i cannot compile mlls, so kindly if you have a newer version i can test, i will be very happy to feed my curiosity..

**Comment by Ziriax** [comment]
No the version in `develop` is not released yet, you have to build that from source.

I don't have time right now, I'm not at the office, but I will prepare an executable for you, so you can test this. I hope to get this done by Monday.

**Comment by readergeneral** [comment]
thank you ziriax 
so much appreciation..

**Comment by Ziriax** [comment]
Please find attached a version for Maya 2019 for you to test. 

After installing it, export as usual, but pass the following extra flags, to **s**eparate **m**esh and **a**nimation buffers:

`-sma` 

You may also want to experiment with adding the following flags:

`-nbu` (nice buffer URIs)
`-hbu` (hash buffer URIs based on content, same buffers will generate the same hash)

Of course you will have to write your own code to handle these GLTFs, so that the meshes are not loaded twice, etc. 

PS: Thanks @fire for all his contributions, making this
[maya2gltf_1.0_a6a059d_maya_2019.zip](https://github.com/WonderMediaProductions/Maya2glTF/files/4103169/maya2gltf_1.0_a6a059d_maya_2019.zip)
[maya2gltf_1.0_a6a059d_maya_2019.zip](https://github.com/WonderMediaProductions/Maya2glTF/files/4103175/maya2gltf_1.0_a6a059d_maya_2019.zip)

 so incredibly easy! I really should take some time to make this  into a 1.0 Windows/MacOS/Linux release, @fire did most the work already.
