### ISSUE TITLE
PBR maya material does not support double-sided rendering

### ISSUE THREAD

**Issue by Chase-Reid** [WonderMediaProductions/Maya2glTF#34]
Hello!

I have an object that requires double-sided rendering. I do not see an option inside the Maya2GLTF material that provides that functionality. My materials are set to FRONT upon inspection inside of ThreeJS Editor.  This option seems to be stored within the THREE.material.
![image](https://user-images.githubusercontent.com/26173435/42000955-4675ecf4-7a17-11e8-8721-811413a4ec98.png)

The material properties inside of ThreeJS editor provides me with option of rendering the FRONT, BACK, or DOUBLE. 
![image](https://user-images.githubusercontent.com/26173435/42001009-777f5574-7a17-11e8-9399-b7f256db4957.png)

I need this option to be set to DOUBLE. Is there a way to do this with the PBR material?

**Comment by Ziriax** [comment]
That is indeed not yet implemented, but should be very trivial to implement, I'll see what I can do

**Comment by Chase-Reid** [comment]
Thanks Ziriax! Youre the best :)

**Comment by Ziriax** [comment]
@Chase-Reid It is a tad harder than I anticipated.

In glTF, the `doublesided` property is on the PBR material.

But in Maya, double-sided is achieved by setting `backface culling` in the shape's attribute editor `Mesh Component Display` (and it seems that double-sided is the default, since backface culling is `off` by default)

Since a Maya PBR shader can be shared amount multiple objects, but each object could have a different `backface culling` setting, I would need to generate different PBR materials for the same Maya PBR shader.

Doable, but a bit harder. 

Out of curiosity, how would you make a double-sided / single-sided object in Maya?

PS: I'm on vacation for two weeks, so don't expect this to be added very soon :wink:

**Comment by Chase-Reid** [comment]
Hmm thats a tough question. To replicate double-sided behavior in Maya I would just toggle off backface culling in the Viewport. 

Im a 3D artist working with game engines so Ive relied on external editors to provide this functionality outside of Maya (Unreal, Unity, etc). These external editors often provide this functionality within their material properties.

Ill look into it though to see if I can give you a better answer on this.  😄

**Comment by Ziriax** [comment]
Then the easiest would be to add a "double-sided" attribute to my PBR material itself. I could even connect this attribute to the Maya shape's backface culling so that it renders correct in Maya. The limitation being that if you manually reuse the same PBR material on other Maya shapes, that the backface culling of this other shapes will not be correct unless the link is restored. But that is a corner case

I will do it like this, that is very easy to do.

**Comment by artistneel** [comment]
is there any solution?

**Comment by Ziriax** [comment]
I will try to make a new release this week to address this issue

**Comment by Ziriax** [comment]
I added a flag to the "PBR Advanced" group in the shader, and perform back-full culling in the shader. I currently ignore the Maya component display mesh backface culling attribute (might be confusing, but ignoring the "double sided" flag in the PBR material would be even stranger IMHO). 

Release coming up tomorrow.

**Comment by Ziriax** [comment]
This should be fixed by [V0.9.8-alpha](../releases/tag/V0.9.8-alpha) (224bdcad245f1f1fde674e5fc1f24235901fff13)
