### ISSUE TITLE
Add refraction 

### ISSUE THREAD

**Issue by artistneel** [WonderMediaProductions/Maya2glTF#43]
Is there any way to add or fake refraction in shaders.

**Comment by Ziriax** [comment]
Refraction is not part of the GLTF spec, so unfortunately, no.

Furthermore refraction is really hard to do right with real-time rasterizing shaders.

That being said, if Nvidia's RTX or Microsoft's DXR takes of, this will be possible simply because ray-tracing will finally become real-time.

A lot of tricks exist to do this with current gen hardware, like phenomenological transparency, but that is outside the scope of this exporter.
