### ISSUE TITLE
The glTF file its empty

### ISSUE THREAD

**Issue by Tresdesero** [WonderMediaProductions/Maya2glTF#63]
Hi, Im new here

I follow the instruction to install glTF exporter for maya but it doesnt work for me
Maya create a glTF file and .bin too, but Maya and Substance cant read it

There is not GLB format for geometry, just glTF, is it correct?

Maya error: "Unrecognized file type"
Substance error: "[Scene 3D] Failed to load 3D scene.
No meshes in scene"

Any suggestion?
Thanks

**Comment by Ziriax** [comment]
GLB should work, but I haven't tested that one lately. I am currently working on the exporter, and will check the GLB feature. This is enabled by passing the `-glb` extra flag.

If you can share the exported GLTF + bin with me privately (email = peter at wonder dot media), I can take a look at what is wrong.

A really helpful tool is VSCODE with the GLTF plugin, that will give a lot of feedback, and has different viewers

**Comment by Tresdesero** [comment]
Thanks so mutch!!

`-glb` flag is working perfectly. Yeah I'll send you this files + (.GLB)
And im going to try VSCODE

Thanks again

**Comment by Ziriax** [comment]
At first sight, it seems both Substance and Maya have poor GLTF importers.

Your model is fine according to the GLTF validator, so should import in any compliant software. 

Unfortunately a lot of software is buggy or only has partial support, or depends on some specific order of elements in the JSON file,...

For example, Substance also had problems importing a GLTF file exported with the Babylon JS exporter :

https://forum.allegorithmic.com/index.php?topic=25155.0

Happy to see GLB works for you.

Closing since there is not much I can do about this.
