### ISSUE TITLE
Maya GLTF Plugin not working

### ISSUE THREAD

**Issue by watsonrock1** [WonderMediaProductions/Maya2glTF#65]
I have no Idea the depoly.bat is not working. I cant install the plugin, I cannot export as GLTF. 
Pls help.
![screenshot_1](https://user-images.githubusercontent.com/42259994/50672362-a4f25c00-0ffd-11e9-8d37-9b6806db7a27.jpg)

**Comment by Ziriax** [comment]
What version of Maya2glTF are you installing, and what version of Maya are you using?


Does installing https://go.microsoft.com/fwlink/?LinkId=746572 help?


Does restarting Maya help?

**Comment by watsonrock1** [comment]
Hi Ziriax Yes I installed all those but it not working.

I am using 2015 and 2018 Maya

**Comment by Ziriax** [comment]
Thanks for the feedback.

Maya 2015 is not supported, 2018 should be.

I couple more questions:

1. What [release](https://github.com/WonderMediaProductions/Maya2glTF/releases) of Maya2glTF are you installing?

2. Since the Maya2glTF UI pops up in Maya, the batch file did copy the MEL scripts. Could you use Windows File Explorer and nagivate to `%userprofile%\Documents\maya\2018\plug-ins`, and check that this directory contains `maya2glTF.mll`? To easily do that, press <kbd>![Windows Key][winlogo]</kbd>+<kbd>E</kbd>, and paste `%userprofile%\Documents\maya\2018\plug-ins` in the address bar at the top.

[winlogo]: http://i.stack.imgur.com/B8Zit.png

**Comment by Ziriax** [comment]
Closing because of no feedback
