### ISSUE TITLE
Error on undefined numbers

### ISSUE THREAD

**Issue by fi4sk0** [WonderMediaProductions/Maya2glTF#70]
Hey there,

We exported a model, that the threeJS gltf loader couldn't parse. After some investigation we found that the gltf file contains the following lines,
```
    }, {
        "bufferView": 2,
        "byteOffset": 4636752,
        "componentType": 5126,
        "count": 260,
        "max": [, , , -1.0], // <-- here
        "min": [, , , -1.0], // <-- here
        "type": "VEC4"
    }, {
        "bufferView": 3,
        "byteOffset": 2241736,
        "componentType": 5126,
        "count": 260,
        "max": [, ], // <-- here
        "min": [, ], // <-- here
        "type": "VEC2"
    }, {
```
which don't evaluate to valid JSON. When I fill the missing spots in the array with some random numbers, the model loads albeit with some quirks, obviously.

Exporting and importing into three.js worked fine, until we added some new parts to it. Not exporting those added parts results in a valid gltf file. So the actual question is: Could you help us track down what we did wrong on our end? Can we unlock additional error messages to see where empty values are written?

Thanks in advance!

**Comment by Ziriax** [comment]
Interesting! I guess these are invalid UV coordinates and tangent vectors.

Could you try to export with the `-mts` as extra flags? You might get more error information (it will use MikkT tangent space code to regenerate the tangents as required by GLTF, Maya's tangents are not 100% compatible).

I guess you can't share your Maya model with me?

**Comment by Ziriax** [comment]
Interesting! I guess these are invalid UV coordinates and tangent vectors.

Could you try to export with the `-mts` as extra flags? You might get more error information (it will use MikkT tangent space code to regenerate the tangents as required by GLTF, Maya's tangents are not 100% compatible).

I guess you can't share your Maya model with me?

**Comment by fi4sk0** [comment]
We re-exported the model using `-mts` and most interestingly, the empty `VEC4` arrays are now gone. However, the problem still persists with `VEC2` like this
```
    }, {
        "bufferView": 3,
        "byteOffset": 2038792,
        "componentType": 5126,
        "count": 260,
        "max": [, ],
        "min": [, ],
        "type": "VEC2"
    }, {
```
Unfortunately I don't have the logging output with the `-mts` (since it's not me exporting), but I can send you the Maya file. I'll get in touch with you.

**Comment by Ziriax** [comment]
This must mean that your Maya model contains `NaN` UVs I guess, very interesting...

**Comment by Ziriax** [comment]
I need a bit more to investigate this, but it seems your model doesn't have UVs for some parts. 

Anyway, in your case you can export your model by disabling the export of texture coordinates and tangents, just type (or paste) the following in the extra flags:

```
-mpa POSITION|NORMAL
```

If we are going to assign vertex colors, then append  `|COLOR` to this line.

**Comment by Ziriax** [comment]
It seems your model just has invalid texture coordinates in Maya itself, so the exporter just writes out this information.

To fix this, select all your (or just the bad) meshes, and generate UV coordinates for them: in Maya, `Modelling` workspace, `UV` menu, select `Automatic`.

Closing this, since nothing wrong with the exporter itself :)

PS: I could add a feature that checks for these invalid texture coordinates, but that would slow down the exporter. **What I did to find out what was wrong, is to pass the `-dac` extra flag**. You will then find a bunch of `txt` files next to your exported model. In Windows Explorer (or any search tool), I go to this directory, and then search for `nan` or `inf`. This finds the following files:
```
polySurfaceShape15_0_vertices_TEXCOORD_0.txt"
polySurfaceShape13_0_vertices_TEXCOORD_0.txt"
```

So in Maya, `select polySurfaceShape15 polySurfaceShape13` to find the misbehaving geometry, and fix these by assigning UV coordinates.

**Comment by fi4sk0** [comment]
I'd argue that the exporter should either throw an error or generate a valid gltf file, warning about the invalid texture coordinates and zero out the invalid values in the output. 

But really, thanks for your help, you're awesome!

**Comment by Ziriax** [comment]
Actually the GLTF library I use from COLLADA2GLTF does print an obscure error at the end:
```
maya2glTF [15:02:23] Failed to reformat glTF JSON, outputting raw JSON
```

I will consider a simple checkbox in the UI that passes a `-verify` flag to the exporter, that checks for these problems. Since I don't know yet all the problems that can occur when exporting, feedback like yours is very welcome!
