### ISSUE TITLE
Support blend shape names

### ISSUE THREAD

**Issue by fire** [WonderMediaProductions/Maya2glTF#73]
https://github.com/KhronosGroup/glTF/issues/1036 Describes a few ways to export blend shape / morph target names.

**Comment by fire** [comment]
See https://github.com/KhronosGroup/glTF-Blender-IO/pull/491

**Comment by imgntn** [comment]
+1 would love this feature!

**Comment by Ziriax** [comment]
No problem, would be very easy. Most work has currently been done in another branch though, and we were able to export most of our inhouse characters, so I'm planning to do a 1.0 release.

But I'll provide this feature first, also sorting by morph-target-name, to get stable ordering between exports.

**Comment by Ziriax** [comment]
I'm sorry but we are currently code-rushing for a deadline, so I'll get back to this ASAP

**Comment by fire** [comment]
Ping!

**Comment by Ziriax** [comment]
Sorry, still very busy with other projects :(

Please bare in mind this is an open source project, so pull requests to implement this are welcome!

**Comment by BigRoy** [comment]
@Ziriax you mentioned this is available in another branch. Do you have any pointers on where it is and how we could easily expose it to the master branch? I noticed [this commit related to blendshapes](https://github.com/WonderMediaProductions/Maya2glTF/commit/bfb2b9118d561f06905284d74d462861dfbde777) since it also mentions that it stores [the blendshape weights by name](https://github.com/WonderMediaProductions/Maya2glTF/commit/bfb2b9118d561f06905284d74d462861dfbde777#diff-2f8fa3cb3644656d7e5a73ef00fcd865R15):

> The weights are sorted by the plug names, to get a stable ordering even when the plugs are re-ordered between scenes.

**Comment by Ziriax** [comment]
The `develop` branch should be merged with master as soon as I migrated completely to `cmake`. That shouldn't be a lot of work, most of it is already prepared.

The `develop` branch indeed sorts the blend shape weight plugs by name, but that shouldn't be required for this issue.

I think just would modifying [this line](https://github.com/WonderMediaProductions/Maya2glTF/blob/40b77bc6d5b2d2e5a477a247cbf8f074a75dcca5/src/ExportableMesh.cpp#L110) to add the name to the `glMesh` `extras` would do it.

The name of blend shape plug can be extracted [like this](https://github.com/WonderMediaProductions/Maya2glTF/blob/8a041222ae54b0896af435cdb84e6f5a7abaa8ec/src/MeshBlendShapeWeights.cpp#L36)

That is, if the COLLADA2GLTF exporter library that I forked correctly exports the `extras`, otherwise this needs to be fixed too.

**Comment by fire** [comment]
Is anyone doing work on this? Trying to decide if I should work on this.

**Comment by fire** [comment]
```c++
           // std::vector<GLTF::Object> morphs;
            MStatus status;
            for (auto&& shape : mayaMesh->allShapes())
            {
                if (shape->shapeIndex.isBlendShapeIndex())
                {
                    m_weightPlugs.emplace_back(shape->weightPlug);
                    m_initialWeights.emplace_back(shape->initialWeight);
                    glMesh.weights.emplace_back(shape->initialWeight);
                    ///morphs.emplace_back(shape->weightPlug.name(&status).asChar());
                    THROW_ON_FAILURE(status);
                }
            }
           // glMesh.extras.emplace("targetNames", morphs);
```

Here is some pesudocode.

**Comment by fire** [comment]
I had to create gtlf morph target name object.

```
#include "GLTFTargetNames.h"

#include "rapidjson/stringbuffer.h"
#include "rapidjson/writer.h"

std::string GLTF::MorphTargetNames::typeName()
{
    return "morphTargetNames";
}

void GLTF::MorphTargetNames::writeJSON(void* writer, GLTF::Options* options)
{
    GLTF::Object::writeJSON(writer, options);
    rapidjson::Writer<rapidjson::StringBuffer>* jsonWriter = (rapidjson::Writer<rapidjson::StringBuffer>*)writer;
    jsonWriter->StartArray();
    for (auto morph : morphs)
    {
        jsonWriter->String(morph.c_str());
    }
    jsonWriter->EndArray();
}

void GLTF::MorphTargetNames::addName(const std::string morph)
{
    morphs.emplace_back(morph);
}
```

The extension and extras objects need a layer of StartObject and EndObject removed.

**Comment by Ziriax** [comment]
That is wonderful, amazing!

Would it be possible for you to make a pull-request, so we can use the fine tools here on github to discuss about it and to make it easy for me to merge the code?

Just in case you have never done this before, [it is really easy to do](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/)

Again, thanks a lot for your contribution!

**Comment by fire** [comment]
Please test. https://github.com/WonderMediaProductions/Maya2glTF/pull/80 implements the feature.
