### ISSUE TITLE
Maya 2019 support?

### ISSUE THREAD

**Issue by stevetalkowski** [WonderMediaProductions/Maya2glTF#77]
Hello! Any chance this could be recompiled for Maya 2019? I got it to work in 2018.5, however, i'm now on Maya 2019.2. I tried copying the files to the appropriate folders, and also added the plug-ins folder to maya/2019. The command maya2glTF_UI; worked to bring up the menu, but when I tried to export, i got the following error:

// Error: file: C:/Users/MAINGEAR/Documents/maya/2019/scripts/maya2glTF_UI.mel line 193: The specified procedure could not be found.

I inspected the mel file and it appears that it has something to do with the path?

loadPlugin "maya2glTF";

I did manually copy the files over to the appropriate folders in \maya\2019, but don't know if 2019 deals with the plug-ins folder in the same way as previous versions?

Any ideas on how to fix this?

Thx!

-Steve

**Comment by Ziriax** [comment]
The `develop` branch already contains support for Maya 2019, and I also received a pull request for it. 

If you want I can give you a release for testing it?

**Comment by stevetalkowski** [comment]
> The `develop` branch already contains support for Maya 2019, and I also received a pull request for it.
> 
> If you want I can give you a release for testing it?

Hello Ziriax! That would be awesome, and greatly appreciated. I had asked this question to some of my contacts at Autodesk, and they said it would have to be recompiled (which i know absolutely nothing about) for 2019.  I would love to get a build and put it through it's paces. I am currently working on a new project where i'll need to deliver animation cycles for a web-based AR project. Thanks!

**Comment by JunkYardRobotBoy** [comment]
Hi Ziriax
May I please also request a release version for testing. Am having the same issues as @stevetalkowski 
Will test on Junk Yard Robot Boy and more than happy to give feedback on how it performs.
Cheers!

**Comment by Ziriax** [comment]
Sure! If you don't get this by Tuesday, please ping me back.

**Comment by Ziriax** [comment]
Could you guys test this version? Thanks!

[Maya2glTF_V1.0.0.zip](https://github.com/WonderMediaProductions/Maya2glTF/files/3617830/Maya2glTF_V1.0.0.zip)

**Comment by stevetalkowski** [comment]
Hey Peter,


Thanks - i just gave it a try and it loaded up and exported from Maya 2019.2 on Windows 10.


Just to confirm, this ONLY exports meshes, and no joint/skeletal information, correct?


Thx,


-Steve


--

Steve Talkowski
Design. Create. Animate.
http://sketchbot.tv
@stevetalkowski

On September 16, 2019 at 12:17 PM, Peter Verswyvelen <notifications@github.com> wrote:



Could you guys test this version? Thanks!

Maya2glTF_V1.0.0.zip

**Comment by Ziriax** [comment]
No, it should be fully functioning. I will double check to see what went wrong

**Comment by JunkYardRobotBoy** [comment]
Hi guys

Looks like it installed fine for Maya 2019.1

Exported a regular animation with the PBR shader and it worked really well.

I'll see how it goes on a skinned model next and let you know.

Cheers
Gerard

**Comment by Ziriax** [comment]
@stevetalkowski  I tried it with a rigged mesh, and it exports joints and skinning, so if it doesn't work for you, it would be great if you could provide your model.

I will do some more regression testing coming weeks.

**Comment by Ziriax** [comment]
@stevetalkowski Thanks for your model! I exported it, and besides some errors about invalid normals/tangents and different rotation/scaling pivots,  it exports just fine.

The reason you are not seeing a skeleton in the McCurdy viewer, is because it doesn't support displaying a skeleton consisting of both regular nodes and joints, even though GLTF doesn't make a distinction between these. 

See https://github.com/donmccurdy/three-gltf-viewer/issues/101

If you are not using Maya's joint segment scale feature (which is enabled by default, but can safely be disabled if you are not scaling joints), you can export your model with the `-isc` extra flag. Then the skeleton should display in the viewer.

Note that in both cases, the skeleton is present in the output. 

To work around this bug in the viewer (well actually, in ThreeJS), I would have to promote all generated corrector nodes to skin nodes, re-indexing all inverse-bind-matrices, etc... This felt like a lot of effort to work around this limitation of ThreeJS. I think it would be easier to fix this in ThreeJS, because it is not GLTF 2.0 compliant, at least not when it comes to displaying debug information ;-)
