### ISSUE TITLE
Does Maya2glTF support 8 weights?

### ISSUE THREAD

**Issue by fire** [WonderMediaProductions/Maya2glTF#79]
Does this project support 8 bone weights on GLTF2 export?

**Comment by fire** [comment]
```cpp
size_t MeshSkeleton::vertexJointAssignmentSetCount() const
{
    const auto vertexJointAssignmentComponentCount = maxVertexJointAssignmentCount();
    const auto vertexJointAssignmentElementSize = array_size<JointIndices>::size;
    const auto vertexJointAssignmentSetCount = (vertexJointAssignmentComponentCount + vertexJointAssignmentElementSize - 1) / vertexJointAssignmentElementSize;
    return vertexJointAssignmentSetCount;
}
```

This code truncates the joint sets.

```cpp
size_t MeshSkeleton::vertexJointAssignmentSetCount() const
{
    const auto vertexJointAssignmentComponentCount = maxVertexJointAssignmentCount();
    const auto vertexJointAssignmentElementSize = array_size<JointIndices>::size;
    const auto vertexJointAssignmentSetCount = roundf((double)vertexJointAssignmentComponentCount + vertexJointAssignmentElementSize - 1) / vertexJointAssignmentElementSize;
    return vertexJointAssignmentSetCount;
}
```

This alternative preserves it.

**Comment by Ziriax** [comment]
Yes, it should support 8 or more bone weights. But few GLTF renderers will support this.

But to be honest I don't think I ever tried it. Do you have a scene that fails exporting?

My code shouldn't truncate the number of weights, (a+b-1)/b is the integer version to round upwards. The code just makes sure the number of weights is a multiple of 4, as required by the GLTF spec (`float4` is used to hold the weights in groups of 4)

I think your version could create 4 weights too many, for example round(4.0 + 3)/4  would result in 2, but should be 1.

**Comment by Ziriax** [comment]
Yes that is correct, in my code:

` const auto vertexJointAssignmentSetCount = (vertexJointAssignmentComponentCount + vertexJointAssignmentElementSize - 1) / vertexJointAssignmentElementSize;`

that would become

`const auto vertexJointAssignmentSetCount = (7 + 3) / 4;` 

so that becomes 2

But it seems `vertexJointAssignmentComponentCount` is wrong in your case. Could you share you file with me?

**Comment by fire** [comment]
I thought vertexJointAssignmentSetCount was an integer rather than a float? If it truncates, rather than ceil, that's a problem.

I can't share my production files :/

**Comment by Ziriax** [comment]
`vertexJointAssignmentSetCount` is indeed an integer. 

I just use an old trick, `ceil(double(p)/q)` == `(p+q-1)/q`.

That's just because I'm a dinosaur, and I programmed on systems that didn't have floating point units (Amiga 500 etc), and these patterns are hard-wired in my brain ;-)

Truncation (like `floor`) would happen if I just did `p/q`, so if the code was:

`const auto vertexJointAssignmentSetCount = vertexJointAssignmentComponentCount / vertexJointAssignmentElementSize`;

I'm pretty sure this code is correct, if it doesn't work, then something else must be wrong. I will double check as soon as I can, I will add a test model.
